name: LinuxAArch64

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 20.3.0.java11

      - name: Install libraries
        run: sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Make staging directory
        run: mkdir staging

      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}

      - name: Install SYSROOT (Linux)
        run: |
          mkdir -p $HOME/sysroot && cd $HOME/sysroot
          wget "https://drive.google.com/file/d/1Jkay5sYpKbm5Gta9CHE1f28Q82_2yVP9/view?usp=sharing"
          unzip aarch64sysroot.zip
        env:
          SYSROOT: $HOME/sysroot/aarch64



      - name: Gluon Build
        run: mvn -Plinux-aarch64 client:build client:package
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}

      - name: Copy native client to staging
        run: cp -r target/client/x86_64-linux/HelloGluon* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
